/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tz_ndk_jni_ffmpeg_NDKFFmpeg */

#ifndef _Included_com_tz_ffmpeg_NDKFFmpeg
#define _Included_com_tz_ffmpeg_NDKFFmpeg
#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT void JNICALL
Java_com_hipad_ffmpegforwbq_NDKFFmpeg_callFFmpegDecode(
        JNIEnv *env, jobject jobj, jstring inFilePath_, jstring outFilePath_);
#ifdef __cplusplus
}
#endif
#endif
